### ISSUE TITLE
Question: mysql or its alternatives 

### ISSUE THREAD

**Issue by cvega** [OpsRockin/hhvm-for-amazon-linux#1]
I seek to understand why mysql-server is a required dependency versus mysql-devel based on the HHVM docs here: 

https://github.com/facebook/hhvm/wiki/Building%20and%20installing%20HHVM%20on%20Amazon%20Linux%202014.03

**Comment by sawanoboly** [comment]
Hi, do you talk about https://github.com/OpsRockin/hhvm-for-amazon-linux/blob/master/site-cookbooks/hhvm-rpm/attributes/packages.rb#L6 ?

I refer to `my.cnf` which is contained the mysql-server package to get parameter of socket path from when building rpm automatically.

But a hhvm package which was built doesn't depends on mysq-server.  We often use the percona mysql with our hhvm-prm which was build by this repository.

**Comment by cvega** [comment]
-DMYSQL_UNIX_SOCK_ADDR=

Doh! Thanks for the reply.
